### ISSUE TITLE
appctl: failed to detect /data mount for lxc containers

### ISSUE THREAD

**Issue by hlwanghl** [QingCloudAppcenter/ansible-roles#24]
https://github.com/QingCloudAppcenter/Kafka/issues/11

**Comment by spwangxp** [comment]
由于 metadata 里并没有关于这方面的信息。目前想到的方法是比较 /proc/cpuinfo 这个文件的内容，由于 lxc 虚拟化会获取宿主机上的信息，导致 cpuinfo 的信息是宿主机的 ，但是 kvm 则不会暴露宿主机的 cpu 信息。

但是不知道 lxc 会不会修复这个，导致我们这个思路失败。

**Comment by hlwanghl** [comment]
多查几个方案，找最保险的一个。
