### ISSUE TITLE
confd-files 的依赖影响到了 appctl-1.2.1 

### ISSUE THREAD

**Issue by MrYourM** [QingCloudAppcenter/ansible-roles#28]
https://github.com/QingCloudAppcenter/ansible-roles/blob/0e1807c4a8f5fef376584e29781df90aa40c5b38/confd-files/meta/main.yml#L14

该依赖使得 appctl-1.1.3 ctl.sh 替换掉了 appctl-1.2.1 的 ctl.sh

**Comment by hlwanghl** [comment]
嗯，刚才提 PR 了

**Comment by MrYourM** [comment]
[keepalived-1.0.4](https://github.com/QingCloudAppcenter/ansible-roles/commit/b23cfe3c379cd0f84f78809dcd366450b635145d)
[haproxy-1.0.6](https://github.com/QingCloudAppcenter/ansible-roles/commit/3caa4e3804cfd290d4e78ed0a2b1a19907171f6f)
[etcd-1.0.8](https://github.com/QingCloudAppcenter/ansible-roles/commit/1a3a6bb557951df1e6346a898b0975f4177e1e59)
[confd-files-1.0.7](https://github.com/QingCloudAppcenter/ansible-roles/commit/fafffe2fdea361bc0a1bcea33043991a1b30102a)
[caddy-1.1.6](https://github.com/QingCloudAppcenter/ansible-roles/commit/23b62a2eed8c43ed8f4e1492c6ed4a1991efc707)
